#!/usr/bin/env bash

set -e # Exit on failure

# Setup mid_db database
psql postgres -c "create role mid_dev_db_user superuser createdb login;"
createdb -O "mid_dev_db_user" mid_dev_db
psql postgres -c "grant all on database mid_dev_db to $( whoami );"
